# Use the official Node.js 16 image as the base image
FROM node:18

WORKDIR /app

# Set Prisma CLI version
ENV PRISMA_CLI_VERSION=3.0.0

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code to the working directory
COPY . .

# Copy the entry point script
COPY docker-entrypoint.dev.sh ./

# Make the entry point script executable
RUN chmod +x docker-entrypoint.dev.sh

# Generate Prisma client files
RUN npx prisma generate

# Expose the port on which your NestJS app is listening
ARG APP_PORT=3000
ARG BASE_URL='http://localhost:${APP_PORT}}'
EXPOSE ${APP_PORT}

# Use the entry point script to start the container
ENTRYPOINT ["/app/docker-entrypoint.dev.sh"]
