import {
  Injectable,
  NotFoundException,
  ConflictException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '@providers/prisma/prisma.service';
import { PaymentsService } from '@modules/payments/payments.service';
import { BiometricCentersService } from '@modules/biometric-centers/biometric-centers.service';

import {
  Prisma,
  BiometricAppointment,
  AppointmentStatus,
  PaymentStatus,
  SubmissionStatus,
} from '@prisma/client';
import {
  CreateBiometricAppointmentDto,
  UpdateAppointmentStatusDto,
  RescheduleAppointmentDto,
  CompleteBiometricCaptureDto,
  AppointmentFiltersDto,
} from './dto/biometric-appointment.dto';
import { PaginationQueryDto } from '@common/dtos';
import { PaginationUtils } from '@common/utils/pagination.utils';

/**
 * Service for managing biometric appointments
 * Handles appointment lifecycle, payment validation, and business logic
 */
@Injectable()
export class BiometricAppointmentsService {
  private readonly logger = new Logger(BiometricAppointmentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly paymentsService: PaymentsService,
    private readonly biometricCentersService: BiometricCentersService,
  ) {}

  /**
   * Create a new biometric appointment
   * Creates appointment with PENDING status, will be activated by payment webhook
   */
  async createAppointment(
    createDto: CreateBiometricAppointmentDto,
    userId: string,
    createdBy?: string,
  ): Promise<BiometricAppointment> {
    try {
      // 1. Validate form submission exists and belongs to user
      const submission = await this.prisma.formSubmission.findUnique({
        where: { id: createDto.submissionId },
        include: { payment: true },
      });

      if (!submission) {
        throw new NotFoundException(
          `Form submission with ID "${createDto.submissionId}" not found`,
        );
      }

      if (submission.userId !== userId) {
        throw new BadRequestException(
          'You can only book appointments for your own submissions',
        );
      }

      // 2. Check if appointment already exists for this submission
      const existingAppointment =
        await this.prisma.biometricAppointment.findUnique({
          where: { submissionId: createDto.submissionId },
        });

      if (existingAppointment) {
        throw new ConflictException(
          `Appointment already exists for submission "${createDto.submissionId}"`,
        );
      }

      // 3. Validate payment exists and is completed
      if (!submission.payment) {
        throw new BadRequestException(
          'Payment must be created before booking an appointment',
        );
      }

      if (submission.payment.status !== PaymentStatus.COMPLETED) {
        throw new BadRequestException(
          `Payment must be completed before booking an appointment. Current status: ${submission.payment.status}`,
        );
      }

      // 4. Validate biometric center exists and is active
      const center = await this.biometricCentersService.findCenterById(
        createDto.centerId,
      );
      if (!center.isActive) {
        throw new BadRequestException(
          `Biometric center "${center.name}" is not active`,
        );
      }

      // 5. Reference number should already be generated by middleware when form was submitted
      // If no reference number exists, the middleware will generate it when the form status changes
      if (!submission.referenceNumber) {
        this.logger.warn(
          `No reference number found for submission ${createDto.submissionId}. Reference number will be generated by middleware when form status changes to SUBMITTED.`,
        );
      }

      // 6. Check center availability for the requested date/time
      const isAvailable =
        await this.biometricCentersService.checkCenterAvailability(
          createDto.centerId,
          new Date(createDto.appointmentDate),
        );

      if (!isAvailable) {
        throw new BadRequestException(
          `Center is not available for the requested date/time`,
        );
      }

      // 7. Validate appointment date/time
      await this.validateAppointmentDateTime(
        createDto.centerId,
        new Date(createDto.appointmentDate),
        new Date(createDto.appointmentTime),
      );

      // 8. Validate acknowledgments
      if (
        !createDto.confirmationAcknowledged ||
        !createDto.consentAcknowledged ||
        !createDto.termsAcknowledged
      ) {
        throw new BadRequestException(
          'All acknowledgments must be confirmed to book an appointment',
        );
      }

      // 9. Create appointment with PENDING status (will be activated by payment webhook)
      const appointmentData: Prisma.BiometricAppointmentCreateInput = {
        user: { connect: { id: userId } },
        submission: { connect: { id: createDto.submissionId } },
        center: { connect: { id: createDto.centerId } },
        appointmentClass: createDto.appointmentClass || 'REGULAR',
        appointmentTime: new Date(createDto.appointmentTime),
        specialRequirements: createDto.specialRequirements,
        confirmationAcknowledged: createDto.confirmationAcknowledged,
        consentAcknowledged: createDto.consentAcknowledged,
        termsAcknowledged: createDto.termsAcknowledged,
        status: AppointmentStatus.PENDING, // Will be activated by payment webhook
        createdBy,
        lastModifiedBy: createdBy,
      };

      // Use transaction to create appointment and update form submission with reference number
      const result = await this.prisma.$transaction(async (tx) => {
        // Create the appointment
        const appointment = await tx.biometricAppointment.create({
          data: appointmentData,
          include: {
            submission: {
              include: {
                form: {
                  include: {
                    country: true,
                  },
                },
                user: {
                  select: {
                    id: true,
                    firstName: true,
                    lastName: true,
                    email: true,
                  },
                },
              },
            },
            center: {
              select: {
                id: true,
                name: true,
                code: true,
                centerNumber: true,
                address: true,
                city: true,
                state: true,
              },
            },
          },
        });

        // Reference number should already exist from middleware
        // No need to update the submission here

        return appointment;
      });

      this.logger.log(
        `Created biometric appointment: ${result.id} for submission: ${
          createDto.submissionId
        }${
          result.submission.referenceNumber
            ? ` with reference: ${result.submission.referenceNumber}`
            : ''
        }`,
      );

      return result;
    } catch (error) {
      this.logger.error(
        `Failed to create appointment: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  /**
   * Get all appointments with optional filtering and pagination
   */
  async findAllAppointments(
    filters: AppointmentFiltersDto = {},
    pagination: PaginationQueryDto = {},
    userId?: string, // Optional: filter by user (for regular users)
  ) {
    const { page = 1, limit = 10 } = pagination;
    const {
      status,
      appointmentClass,
      centerId,
      submissionId,
      referenceNumber,
      fromDate,
      toDate,
      biometricsCaptured,
    } = filters;

    // Build where clause
    const where: Prisma.BiometricAppointmentWhereInput = {};

    if (userId) {
      where.userId = userId;
    }

    if (filters.userId) {
      where.userId = filters.userId;
    }

    if (status) {
      where.status = status;
    }

    if (appointmentClass) {
      where.appointmentClass = appointmentClass;
    }

    if (centerId) {
      where.centerId = centerId;
    }

    if (submissionId) {
      where.submissionId = submissionId;
    }

    if (referenceNumber) {
      where.submission = {
        referenceNumber: referenceNumber,
      };
    }

    if (fromDate || toDate) {
      where.appointmentTime = {};
      if (fromDate) {
        const startOfDay = new Date(fromDate);
        startOfDay.setHours(0, 0, 0, 0);
        where.appointmentTime.gte = startOfDay;
      }
      if (toDate) {
        const endOfDay = new Date(toDate);
        endOfDay.setHours(23, 59, 59, 999);
        where.appointmentTime.lte = endOfDay;
      }
    }

    if (biometricsCaptured !== undefined) {
      where.biometricsCaptured = biometricsCaptured;
    }

    // Calculate pagination
    const skip = (page - 1) * limit;

    // Execute queries
    const [appointments, totalCount] = await Promise.all([
      this.prisma.biometricAppointment.findMany({
        where,
        skip,
        take: limit,
        orderBy: [{ appointmentTime: 'asc' }],
        include: {
          user: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              email: true,
              nin: true,
            },
          },
          submission: {
            select: {
              id: true,
              status: true,
              referenceNumber: true,
              payment: {
                select: {
                  id: true,
                  status: true,
                  amount: true,
                },
              },
              responses: {
                where: {
                  fieldName: {
                    in: ['passport-photo', 'passport-number'],
                  },
                },
                select: {
                  id: true,
                  fieldName: true,
                  fileUrls: true,
                  value: true,
                  instanceIndex: true,
                },
              },
            },
          },
          center: {
            select: {
              id: true,
              name: true,
              address: true,
              city: true,
              state: true,
            },
          },
        },
      }),
      this.prisma.biometricAppointment.count({ where }),
    ]);

    const meta = PaginationUtils.createPaginationMeta(
      page,
      limit,
      totalCount,
      'appointmentDate',
      'asc',
    );

    return {
      data: appointments,
      meta,
    };
  }

  /**
   * Get a single appointment by ID
   */
  async findAppointmentById(
    id: string,
    userId?: string,
  ): Promise<BiometricAppointment> {
    const where: Prisma.BiometricAppointmentWhereInput = { id };

    if (userId) {
      where.userId = userId;
    }

    const appointment = await this.prisma.biometricAppointment.findFirst({
      where,
      include: {
        user: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            nin: true,
          },
        },
        submission: {
          select: {
            id: true,
            status: true,
            referenceNumber: true,
            payment: {
              select: {
                id: true,
                status: true,
                amount: true,
              },
            },
            responses: {
              where: {
                fieldName: {
                  in: ['passport-photo', 'passport-number'],
                },
              },
              select: {
                id: true,
                fieldName: true,
                fileUrls: true,
                value: true,
                instanceIndex: true,
              },
            },
          },
        },
        center: true,
      },
    });

    if (!appointment) {
      throw new NotFoundException(`Appointment with ID "${id}" not found`);
    }

    return appointment;
  }

  /**
   * Get a single appointment by reference number
   */
  async findAppointmentByReferenceNumber(
    referenceNumber: string,
    userId?: string,
  ): Promise<BiometricAppointment> {
    const where: Prisma.BiometricAppointmentWhereInput = {
      submission: {
        referenceNumber: referenceNumber,
      },
    };

    if (userId) {
      where.userId = userId;
    }

    const appointment = await this.prisma.biometricAppointment.findFirst({
      where,
      include: {
        user: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            nin: true,
          },
        },
        submission: {
          select: {
            id: true,
            status: true,
            referenceNumber: true,
            payment: {
              select: {
                id: true,
                status: true,
                amount: true,
              },
            },
            responses: {
              where: {
                fieldName: {
                  in: ['passport-photo', 'passport-number'],
                },
              },
              select: {
                id: true,
                fieldName: true,
                fileUrls: true,
                value: true,
                instanceIndex: true,
              },
            },
          },
        },
        center: {
          select: {
            id: true,
            name: true,
            address: true,
            city: true,
            state: true,
          },
        },
        biometricSession: {
          select: {
            id: true,
            photoCaptured: true,
            fingerprintsCaptured: true,
            signatureCaptured: true,
            startedAt: true,
            completedAt: true,
            booth: {
              select: {
                id: true,
                boothNumber: true,
                isActive: true,
                isOccupied: true,
              },
            },
          },
        },
        queueEntry: {
          select: {
            id: true,
            boothId: true,
            status: true,
            booth: {
              select: {
                id: true,
                boothNumber: true,
                isActive: true,
                isOccupied: true,
              },
            },
          },
        },
      },
    });

    if (!appointment) {
      throw new NotFoundException(
        `Appointment with reference number "${referenceNumber}" not found`,
      );
    }

    // Add computed status fields for better API response
    const appointmentWithStatus = {
      ...appointment,
      // Booth assignment status
      assignedToBooth:
        appointment.status === 'AT_BOOTH' ||
        !!appointment.biometricSession ||
        !!appointment.queueEntry?.boothId,

      // Capture status - check both formal session and direct capture
      photoCaptured:
        appointment.biometricSession?.photoCaptured ??
        (appointment.biometricsCaptured && appointment.capturedAt
          ? true
          : false),

      fingerprintsCaptured:
        appointment.biometricSession?.fingerprintsCaptured ??
        (appointment.biometricsCaptured && appointment.capturedAt
          ? true
          : false),

      signatureCaptured:
        appointment.biometricSession?.signatureCaptured ?? false,
    };

    return appointmentWithStatus;
  }

  /**
   * Update appointment status (admin use)
   */
  async updateAppointmentStatus(
    id: string,
    updateDto: UpdateAppointmentStatusDto,
    lastModifiedBy?: string,
  ): Promise<BiometricAppointment> {
    try {
      const appointment = await this.findAppointmentById(id);

      // Validate status transition
      this.validateStatusTransition(appointment.status, updateDto.status);

      const updatedAppointment = await this.prisma.biometricAppointment.update({
        where: { id },
        data: {
          status: updateDto.status,
          adminNotes: updateDto.adminNotes,
          lastModifiedBy,
        },
        include: {
          user: true,
          submission: true,
          center: true,
        },
      });

      this.logger.log(
        `Updated appointment ${id} status to ${updateDto.status}`,
      );

      return updatedAppointment;
    } catch (error) {
      this.logger.error(
        `Failed to update appointment status ${id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  /**
   * Reschedule an appointment
   */
  async rescheduleAppointment(
    id: string,
    rescheduleDto: RescheduleAppointmentDto,
    userId?: string,
    lastModifiedBy?: string,
  ): Promise<BiometricAppointment> {
    try {
      const appointment = await this.findAppointmentById(id, userId);

      if (!this.canReschedule(appointment.status)) {
        throw new BadRequestException(
          `Cannot reschedule appointment with status: ${appointment.status}`,
        );
      }

      // Validate new center if provided
      const centerId = rescheduleDto.centerId || appointment.centerId;
      if (rescheduleDto.centerId) {
        const center = await this.biometricCentersService.findCenterById(
          centerId,
        );
        if (!center.isActive) {
          throw new BadRequestException(
            `Biometric center "${center.name}" is not currently active`,
          );
        }
      }

      // Validate new appointment date/time
      await this.validateAppointmentDateTime(
        centerId,
        new Date(rescheduleDto.appointmentDate),
        new Date(rescheduleDto.appointmentTime),
        id, // Exclude current appointment from conflict check
      );

      const updatedAppointment = await this.prisma.biometricAppointment.update({
        where: { id },
        data: {
          originalAppointmentDate:
            appointment.originalAppointmentDate || appointment.appointmentTime,
          appointmentTime: new Date(rescheduleDto.appointmentTime),
          centerId,
          rescheduleReason: rescheduleDto.rescheduleReason,
          rescheduleCount: { increment: 1 },
          status: AppointmentStatus.RESCHEDULED,
          lastModifiedBy,
        },
        include: {
          user: true,
          submission: true,
          center: true,
        },
      });

      this.logger.log(
        `Rescheduled appointment ${id} to ${rescheduleDto.appointmentDate} ${rescheduleDto.appointmentTime}`,
      );

      return updatedAppointment;
    } catch (error) {
      this.logger.error(
        `Failed to reschedule appointment ${id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  /**
   * Complete biometric capture
   */
  async completeBiometricCapture(
    id: string,
    captureDto: CompleteBiometricCaptureDto,
    capturedBy: string,
  ): Promise<BiometricAppointment> {
    try {
      const appointment = await this.findAppointmentById(id);

      const validStatuses = [
        AppointmentStatus.AT_BOOTH,
        AppointmentStatus.IN_QUEUE,
      ];
      if (!validStatuses.includes(appointment.status as any)) {
        throw new BadRequestException(
          `Can only complete biometric capture for appointments at booth or in queue. Current status: ${appointment.status}`,
        );
      }
      const result = await this.prisma.$transaction(async (tx) => {
        const completionTime = new Date();

        // 1) Update appointment to COMPLETED
        const updatedAppointment = await tx.biometricAppointment.update({
          where: { id },
          data: {
            status: AppointmentStatus.COMPLETED,
            biometricsCaptured: true,
            capturedAt: completionTime,
            capturedBy,
            captureQuality: captureDto.captureQuality,
            adminNotes: captureDto.adminNotes,
            lastModifiedBy: capturedBy,
          },
          include: {
            user: true,
            submission: true,
            center: true,
          },
        });

        // 2) Mark submission as biometric completed and move to UNDER_REVIEW with status log
        if (appointment.submissionId) {
          const fromStatus = updatedAppointment.submission?.status;
          await tx.formSubmission.update({
            where: { id: appointment.submissionId },
            data: {
              status: SubmissionStatus.UNDER_REVIEW,
              biometricCompleted: true,
              biometricCompletedAt: completionTime,
              statusLogs: {
                create: {
                  fromStatus: fromStatus || undefined,
                  toStatus: SubmissionStatus.UNDER_REVIEW,
                  reason: 'Biometric capture completed',
                  notes: captureDto.adminNotes,
                  changedBy: capturedBy,
                },
              },
            },
          });
        }

        // 3) Update queue entry to COMPLETED
        const queueEntry = await tx.queueEntry.findFirst({
          where: { appointmentId: id },
        });
        if (queueEntry) {
          await tx.queueEntry.update({
            where: { id: queueEntry.id },
            data: {
              status: 'COMPLETED',
              completedAt: completionTime,
            },
          });
        }

        return updatedAppointment;
      });

      this.logger.log(
        `Completed biometric capture for appointment ${id} by ${capturedBy}`,
      );

      return result;
    } catch (error) {
      this.logger.error(
        `Failed to complete biometric capture ${id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  /**
   * Cancel an appointment
   */
  async cancelAppointment(
    id: string,
    reason: string,
    userId?: string,
    lastModifiedBy?: string,
  ): Promise<BiometricAppointment> {
    try {
      const appointment = await this.findAppointmentById(id, userId);

      if (!this.canCancel(appointment.status)) {
        throw new BadRequestException(
          `Cannot cancel appointment with status: ${appointment.status}`,
        );
      }

      const updatedAppointment = await this.prisma.biometricAppointment.update({
        where: { id },
        data: {
          status: AppointmentStatus.CANCELLED,
          adminNotes: reason,
          lastModifiedBy,
        },
        include: {
          user: true,
          submission: true,
          center: true,
        },
      });

      this.logger.log(`Cancelled appointment ${id}: ${reason}`);

      return updatedAppointment;
    } catch (error) {
      this.logger.error(
        `Failed to cancel appointment ${id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  /**
   * Get appointment statistics
   */
  async getAppointmentStatistics(centerId?: string) {
    const where = centerId ? { centerId } : {};

    const [
      totalAppointments,
      activeAppointments,
      completedAppointments,
      pendingAppointments,
      cancelledAppointments,
      statusBreakdown,
    ] = await Promise.all([
      this.prisma.biometricAppointment.count({ where }),
      this.prisma.biometricAppointment.count({
        where: { ...where, status: AppointmentStatus.ACTIVE },
      }),
      this.prisma.biometricAppointment.count({
        where: { ...where, status: AppointmentStatus.COMPLETED },
      }),
      this.prisma.biometricAppointment.count({
        where: { ...where, status: AppointmentStatus.PENDING },
      }),
      this.prisma.biometricAppointment.count({
        where: { ...where, status: AppointmentStatus.CANCELLED },
      }),
      this.prisma.biometricAppointment.groupBy({
        by: ['status'],
        where,
        _count: { _all: true },
      }),
    ]);

    return {
      totalAppointments,
      activeAppointments,
      completedAppointments,
      pendingAppointments,
      cancelledAppointments,
      statusBreakdown,
      completionRate:
        totalAppointments > 0
          ? (completedAppointments / totalAppointments) * 100
          : 0,
    };
  }

  /**
   * Validate appointment date and time
   */
  private async validateAppointmentDateTime(
    centerId: string,
    appointmentDate: Date,
    appointmentTime: Date,
    excludeAppointmentId?: string,
  ): Promise<void> {
    // Check if date is in the future
    const now = new Date();
    if (appointmentDate < now) {
      throw new BadRequestException('Appointment date must be in the future');
    }

    // Check center availability for the date
    const isAvailable =
      await this.biometricCentersService.checkCenterAvailability(
        centerId,
        appointmentDate,
      );

    if (!isAvailable) {
      throw new BadRequestException(
        'Biometric center is not available on the selected date',
      );
    }

    // Check for conflicting appointments at the same time slot
    const conflictingAppointment =
      await this.prisma.biometricAppointment.findFirst({
        where: {
          centerId,
          appointmentTime,
          status: {
            in: [AppointmentStatus.ACTIVE, AppointmentStatus.SCHEDULED],
          },
          ...(excludeAppointmentId && { id: { not: excludeAppointmentId } }),
        },
      });

    if (conflictingAppointment) {
      throw new BadRequestException('The selected time slot is already booked');
    }
  }

  /**
   * Validate status transition
   */
  private validateStatusTransition(
    currentStatus: AppointmentStatus,
    newStatus: AppointmentStatus,
  ): void {
    const validTransitions: Record<AppointmentStatus, AppointmentStatus[]> = {
      [AppointmentStatus.PENDING]: [
        AppointmentStatus.ACTIVE,
        AppointmentStatus.CANCELLED,
      ],
      [AppointmentStatus.SCHEDULED]: [
        AppointmentStatus.ACTIVE,
        AppointmentStatus.RESCHEDULED,
        AppointmentStatus.CANCELLED,
      ],
      [AppointmentStatus.ACTIVE]: [
        AppointmentStatus.CHECKED_IN,
        AppointmentStatus.COMPLETED,
        AppointmentStatus.RESCHEDULED,
        AppointmentStatus.CANCELLED,
        AppointmentStatus.NO_SHOW,
      ],
      [AppointmentStatus.CHECKED_IN]: [
        AppointmentStatus.IN_QUEUE,
        AppointmentStatus.CANCELLED,
        AppointmentStatus.NO_SHOW,
      ],
      [AppointmentStatus.IN_QUEUE]: [
        AppointmentStatus.AT_BOOTH,
        AppointmentStatus.CANCELLED,
        AppointmentStatus.NO_SHOW,
      ],
      [AppointmentStatus.AT_BOOTH]: [
        AppointmentStatus.COMPLETED,
        AppointmentStatus.CANCELLED,
      ],
      [AppointmentStatus.COMPLETED]: [], // Final state
      [AppointmentStatus.CANCELLED]: [AppointmentStatus.PENDING], // Can restart
      [AppointmentStatus.RESCHEDULED]: [
        AppointmentStatus.ACTIVE,
        AppointmentStatus.CANCELLED,
      ],
      [AppointmentStatus.NO_SHOW]: [], // Final state
    };

    if (!validTransitions[currentStatus]?.includes(newStatus)) {
      throw new BadRequestException(
        `Invalid status transition from ${currentStatus} to ${newStatus}`,
      );
    }
  }

  /**
   * Check if appointment can be rescheduled
   */
  private canReschedule(status: AppointmentStatus): boolean {
    const allowedStatuses = [
      AppointmentStatus.PENDING,
      AppointmentStatus.SCHEDULED,
      AppointmentStatus.ACTIVE,
      AppointmentStatus.RESCHEDULED,
    ] as AppointmentStatus[];
    return allowedStatuses.includes(status);
  }

  /**
   * Check if appointment can be cancelled
   */
  private canCancel(status: AppointmentStatus): boolean {
    const allowedStatuses = [
      AppointmentStatus.PENDING,
      AppointmentStatus.SCHEDULED,
      AppointmentStatus.ACTIVE,
      AppointmentStatus.RESCHEDULED,
    ] as AppointmentStatus[];
    return allowedStatuses.includes(status);
  }
}
